// AUTO-GENERATED BY StringEnumLibrary - DO NOT EDIT BY HAND
// Source asset: Assets/Enums.asset
// Generated at: 2025-12-16 08:30:36

namespace Core.Enums
{
    public static class ammo
    {
        public static readonly SerialEnum emp = new SerialEnum("ammo.emp");
        public static readonly SerialEnum explosive = new SerialEnum("ammo.explosive");
        public static readonly SerialEnum large = new SerialEnum("ammo.large");
        public static readonly SerialEnum medium = new SerialEnum("ammo.medium");
        public static readonly SerialEnum small = new SerialEnum("ammo.small");
    }

    public static class rarity
    {
        public static readonly SerialEnum common = new SerialEnum("rarity.common");
        public static readonly SerialEnum epic = new SerialEnum("rarity.epic");
        public static readonly SerialEnum exhalted = new SerialEnum("rarity.exhalted");
        public static readonly SerialEnum legendary = new SerialEnum("rarity.legendary");
        public static readonly SerialEnum rare = new SerialEnum("rarity.rare");
        public static readonly SerialEnum trash = new SerialEnum("rarity.trash");
        public static readonly SerialEnum uncommon = new SerialEnum("rarity.uncommon");
    }

}
